In [2]:
import numpy as np

## L6

### 5. Review: Empirical Mean and Covariance Matrix of a Vector Data Set I

In [182]:
# The Sample Covariance for a Data Set of Vectors
# empirical covariance matrix or sample covariance matrix
x1 = np.array([8,4,7])
x2 = np.array([2,8,1])
x3 = np.array([3,1,1])
x4 = np.array([9,7,4])

X = np.vstack([x1,x2,x3,x4])
X

array([[8, 4, 7],
       [2, 8, 1],
       [3, 1, 1],
       [9, 7, 4]])

In [183]:
bar_X = np.mean(X, axis=0)
bar_X, np.outer(bar_X, bar_X)

(array([5.5 , 5.  , 3.25]),
 array([[30.25  , 27.5   , 17.875 ],
        [27.5   , 25.    , 16.25  ],
        [17.875 , 16.25  , 10.5625]]))

In [184]:
S,S_np

(array([[9.25  , 1.    , 6.375 ],
        [1.    , 7.5   , 0.    ],
        [6.375 , 0.    , 6.1875]]),
 array([[9.25  , 1.    , 6.375 ],
        [1.    , 7.5   , 0.    ],
        [6.375 , 0.    , 6.1875]]))

In [185]:
S = (np.mean([np.outer(x1, x1),np.outer(x2, x2),np.outer(x3, x3),np.outer(x4, x4)],axis=0))-np.outer(bar_X, bar_X)
# np.cov is feature wise cov if we want sample wise, DATA.T
S_np=np.cov(X.T,bias=True)

print(f'sample covariance matrix= \n {S}, S == S_np? {(S==S_np).all()}')

sample covariance matrix= 
 [[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]], S == S_np? True


In [189]:
# other solution
n=X.shape[0]
S = 1/n*np.matmul(np.matmul(X.T , np.identity(X.shape[0])-1/n*np.outer(np.ones(n),np.ones(n))), X)
S

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

### 6. Empirical Mean and Covariance Matrix of a Vector Data Set II

In [190]:
# An Orthogonal Projection Matrix
n=3
H = np.identity(3)-1/3*np.outer(np.ones(3),np.ones(3)) 
x = np.array([2,-1,-2])
H,x,H**2

(array([[ 0.66666667, -0.33333333, -0.33333333],
        [-0.33333333,  0.66666667, -0.33333333],
        [-0.33333333, -0.33333333,  0.66666667]]),
 array([ 2, -1, -2]),
 array([[0.44444444, 0.11111111, 0.11111111],
        [0.11111111, 0.44444444, 0.11111111],
        [0.11111111, 0.11111111, 0.44444444]]))

In [191]:
np.dot(H,x), np.dot(np.matmul(H,H),x)

(array([ 2.33333333, -0.66666667, -1.66666667]),
 array([ 2.33333333, -0.66666667, -1.66666667]))

- For any positive integer 𝑘 and any vector $𝐱 \in \mathbb{R}^n$, we have $𝐻^k 𝐱= 𝐻𝐱$.
- The matrix $𝐻$  is a projection onto the subspace of vectors perpendicular to the vector $\vec{1} \in \mathbb{R}^n$ , which has all of its entries equal to  1 .
- The matrix  𝐻  is a projections onto the subspace  ${𝐱:\frac{1}{𝑛}\sum\limits_{i=1}^{n}{x^i}=0}\subset \mathbb{R}^n$ . (In other words, this is the set of vectors having coordinate-wise average equal to  0 .)

### 7. Measuring the Spread of a Point Cloud

In [57]:
# Projection onto a Line
u=1/np.sqrt(5)*np.array([1,2])
x1=np.array([1,2])
x2=np.array([3,4])
x3=np.array([-1,0])

In [58]:
np.dot(u,x1)*u, np.dot(u,x2)*u, np.dot(u,x3)*u

(array([1., 2.]), array([2.2, 4.4]), array([-0.2, -0.4]))

In [59]:
# Empirical Variance of a Data Set in a Given Direction
X = np.vstack([np.dot(u,x1), np.dot(u,x2), np.dot(u,x3)])
bar_x = np.mean(X)
np.mean([(np.dot(u,x1)-bar_x)**2,(np.dot(u,x2)-bar_x)**2, (np.dot(u,x3)-bar_x)**2])

4.8

In [60]:
#   𝐮^T𝑆𝐮
n=X.shape[0]
S = 1/n*np.matmul(np.matmul(X.T , np.identity(X.shape[0])-1/n*np.outer(np.ones(n),np.ones(n))), X)
np.matmul(np.matmul(np.expand_dims(u,-1),np.squeeze(S, axis=-1)),u)

4.799999999999999

In [61]:
# Variance of a Random Vector in a Given Direction
((1-np.sqrt(3))**2+(3-np.sqrt(3))**2+(-1-np.sqrt(3))**2)/3

3.202565051528912

### 12. Conceptual Examples Continued

In [67]:
𝐱_1 	 = 	 np.array((0,2))
𝐱_2 	 = 	 np.array((0,-2))
𝐱_3 	 = 	 np.array((1,1))
𝐱_4 	 = 	 np.array((-1,-1))
X=np.vstack([x_1,x_2,x_3,x_4])
X

array([[ 0,  2],
       [ 0, -2],
       [ 1,  1],
       [-1, -1]])

In [68]:
# covariance matrix
S =np.cov(X.T,bias=True)
S == 1/4*np.dot(X.T,X)

array([[ True,  True],
       [ True,  True]])

In [69]:
e_values, e_vectors = np.linalg.eig(S)
e_values_matrix = np.diag(e_values)
e_values_matrix, e_vectors

(array([[0.38196601, 0.        ],
        [0.        , 2.61803399]]),
 array([[-0.97324899, -0.22975292],
        [ 0.22975292, -0.97324899]]))

In [70]:
S == np.round(np.matmul(np.matmul(e_vectors,e_values_matrix), e_vectors.T),1)

array([[ True,  True],
       [ True,  True]])

### opinal

In [101]:
𝐱_1 	 = 	 np.array((1,1/2))
𝐱_2 	 = 	 np.array((-1,-1/2))
X=np.vstack([x_1,x_2])
X
print(f'ds = \n{X}')
# covariance matrix
S =np.cov(X.T,bias=True)
print(f'covariance matrix = \n{S}')
print(S == 1/X.shape[0]*np.dot(X.T,X)-np.outer(np.mean(X,axis=0),np.mean(X,axis=0).T))
e_values, e_vectors = np.linalg.eig(S)
e_values_matrix = np.diag(e_values)
print(f'e_values_matrix = \n {e_values_matrix}')
print(f'e_vectors_matrix = \n {e_vectors}')
print(f'x_1 projected = \n {np.dot(e_vectors[:,0],x_1)}')
print(f'x_2 projected = \n {np.dot(e_vectors[:,0],x_2)}')

ds = 
[[ 1.   0.5]
 [-1.  -0.5]]
covariance matrix = 
[[1.   0.5 ]
 [0.5  0.25]]
[[ True  True]
 [ True  True]]
e_values_matrix = 
 [[1.25 0.  ]
 [0.   0.  ]]
e_vectors_matrix = 
 [[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
x_1 projected = 
 1.118033988749895
x_2 projected = 
 -1.118033988749895


In [105]:
𝐱_1 	 = 	 np.array((0,2))
𝐱_2 	 = 	 np.array((1,-1))
𝐱_3 	 = 	 np.array((-1,-1))
X=np.vstack([x_1,x_2,x_3])
X
print(f'ds = \n{X}')
# covariance matrix
S =np.cov(X.T,bias=True)
print(f'covariance matrix = \n{S}')
print(S == 1/X.shape[0]*np.dot(X.T,X)-np.outer(np.mean(X,axis=0),np.mean(X,axis=0).T))
e_values, e_vectors = np.linalg.eig(S)
e_values_matrix = np.diag(e_values)
print(f'e_values_matrix = \n {e_values_matrix}')
print(f'e_vectors_matrix = \n {e_vectors}')
print(f'x_1 projected = \n {np.dot(e_vectors[:,1],x_1)}')
print(f'x_2 projected = \n {np.dot(e_vectors[:,1],x_2)}')
print(f'x_2 projected = \n {np.dot(e_vectors[:,1],x_3)}')

ds = 
[[ 0  2]
 [ 1 -1]
 [-1 -1]]
covariance matrix = 
[[0.66666667 0.        ]
 [0.         2.        ]]
[[ True  True]
 [ True  True]]
e_values_matrix = 
 [[0.66666667 0.        ]
 [0.         2.        ]]
e_vectors_matrix = 
 [[1. 0.]
 [0. 1.]]
x_1 projected = 
 2.0
x_2 projected = 
 -1.0
x_2 projected = 
 -1.0
